/**
 * Copyright © INOVUA TRADING.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

export default [
  {
    id: 110,
    firstName: 'Bill',
    name: 'Bill',
    student: true,
    age: 20,
    city: 'Manchester',
    country: 'uk',
    email: 'bill@manchester.uk',
    birthDate: 1980,
  },
  {
    id: 1,
    firstName: 'Mary',
    name: 'Mary',
    age: 22,
    student: true,
    city: 'New York',
    country: 'usa',
    email: 'mary.mary@gmail.com',
    birthDate: 1982,
  },
  {
    id: 2,
    firstName: 'John',
    name: 'John',
    age: 32,
    student: false,
    city: 'London',
    country: 'uk',
    email: 'john@London.com',
    birthDate: 1970,
  },
  {
    id: 3,
    firstName: 'Boby',
    name: 'Boby',
    age: 32,
    student: false,
    city: 'Vancouver',
    country: 'ca',
    email: 'boby@vancouver.com',
    birthDate: 1987,
  },
  {
    id: 4,
    firstName: 'Billy',
    name: 'Billy',
    age: 32,
    student: false,
    city: 'Edmonton',
    email: 'billy@edmonton.ca',
    country: 'ca',
    birthDate: 1990,
  },
  {
    id: 5,
    firstName: 'Johny',
    name: 'Johny',
    age: 32,
    student: true,
    city: 'San Jose',
    country: 'usa',
    email: 'johny@yahoo.com',
    birthDate: 1989,
  },
  {
    id: 6,
    firstName: 'Hilly',
    name: 'Hilly',
    age: 32,
    student: true,
    city: 'London',
    country: 'uk',
    email: 'hilly@london.co.uk',
    birthDate: 2010,
  },
  {
    id: 7,
    firstName: 'Hillaay',
    name: 'Hillaay',
    age: 47,
    student: false,
    city: 'Leeds',
    country: 'uk',
    email: 'hillaay@britain.com',
    birthDate: 19897,
  },
  {
    id: 8,
    firstName: 'Matthew',
    name: 'Matthew',
    age: 47,
    student: false,
    city: 'Leeds',
    country: 'uk',
    email: 'matthew@leeds.co.uk',
    birthDate: 2007,
  },
  {
    id: 9,
    firstName: 'David',
    name: 'David',
    age: 48,
    student: false,
    city: 'Toronto',
    country: 'ca',
    email: 'david@toronto.com',
    birthDate: 1979,
  },
  {
    id: 10,
    firstName: 'Richard',
    name: 'Richard',
    age: 9,
    student: false,
    city: 'Ottawa',
    country: 'ca',
    email: 'richard@ottawa.ca',
    birthDate: 2000,
  },
  {
    id: 11,
    firstName: 'Hillary',
    name: 'Hillary',
    age: 34,
    student: true,
    city: 'New York',
    email: 'hillary@gmail.com',
    country: 'usa',
    birthDate: 1982,
  },
];
