/**
 * Copyright © INOVUA TRADING.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

export default [
  { groupa: 'Group number 1', label: 'Afghanistan', id: 'AF' },
  { groupa: 'Group number 1', label: 'Åland Islands', id: 'AX' },
  { groupa: 'Group number 1', label: 'Albania', id: 'AL' },
  { groupa: 'Group number 1', label: 'Algeria', id: 'DZ', disalbed: true },
  { groupa: 'Group number 1', label: 'American Samoa', id: 'AS' },
  { groupa: 'Group number 1', label: 'AndorrA', id: 'AD' },
  { groupa: 'Group number 1', label: 'Angola', id: 'AO' },
  { groupa: 'Group number 1', label: 'Anguilla', id: 'AI', disabled: true },
  { groupa: 'Group number 1', label: 'Antarctica', id: 'AQ' },
  { groupa: 'Group number 1', label: 'Antigua and Barbuda', id: 'AG' },
  { groupa: 'Group number 1', label: 'Argentina', id: 'AR' },
  { groupa: 'Group number 1', label: 'Armenia', id: 'AM' },
  { groupa: 'Group number 1', label: 'Aruba', id: 'AW' },
  { groupa: 'Group number 1', label: 'Australia', id: 'AU' },
  { groupa: 'Group number 1', label: 'Austria', id: 'AT' },
  { groupa: 'Group number 1', label: 'Azerbaijan', id: 'AZ' },
  { groupa: 'Group number 1', label: 'Bahamas', id: 'BS' },
  { groupa: 'Group number 1', label: 'Bahrain', id: 'BH' },
  { groupa: 'Group number 1', label: 'Bangladesh', id: 'BD' },
  { groupa: 'Group number 1', label: 'Barbados', id: 'BB' },
  { groupa: 'Group number 1', label: 'Belarus', id: 'BY' },
  { groupa: 'Group number 1.1', label: 'Belgium', id: 'BE' },
  { groupa: 'Group number 1.1', label: 'Belize', id: 'BZ' },
  { groupa: 'Group number 1.1', label: 'Benin', id: 'BJ' },
  { groupa: 'Group number 1.1', label: 'Bermuda', id: 'BM' },
  { groupa: 'Group number 1.1', label: 'Bhutan', id: 'BT' },
  { groupa: 'Group number 1.1', label: 'Bolivia', id: 'BO' },
  { groupa: 'Group number 1.1', label: 'Bosnia and Herzegovina', id: 'BA' },
  { groupa: 'Group number 1.1', label: 'Botswana', id: 'BW' },
  { groupa: 'Group number 1.1', label: 'Bouvet Island', id: 'BV' },
  { groupa: 'Group number 1.1', label: 'Brazil', id: 'BR' },
  {
    groupa: 'Group number 1.1',
    label: 'British Indian Ocean Territory',
    id: 'IO',
  },
  { groupa: 'Group number 1.1', label: 'Brunei Darussalam', id: 'BN' },
  { groupa: 'Group number 1.1', label: 'Bulgaria', id: 'BG' },
  { groupa: 'Group number 1.2', label: 'Burkina Faso', id: 'BF' },
  { groupa: 'Group number 1.2', label: 'Burundi', id: 'BI' },
  { groupa: 'Group number 1.2', label: 'Cambodia', id: 'KH' },
  { groupa: 'Group number 1.2', label: 'Cameroon', id: 'CM' },
  { groupa: 'Group number 1.2', label: 'Canada', id: 'CA' },
  { groupa: 'Group number 1.2', label: 'Cape Verde', id: 'CV' },
  { groupa: 'Group number 1.2', label: 'Cayman Islands', id: 'KY' },
  { groupa: 'Group number 1.2', label: 'Central African Republic', id: 'CF' },
  { groupa: 'Group number 1.2', label: 'Chad', id: 'TD' },
  { groupa: 'Group number 1.2', label: 'Chile', id: 'CL' },
  { groupa: 'Group number 1.2', label: 'China', id: 'CN' },
  { groupa: 'Group number 1.2', label: 'Christmas Island', id: 'CX' },
  { groupa: 'Group number 1.2', label: 'Cocos (Keeling) Islands', id: 'CC' },
  { groupa: 'Group number 1.2', label: 'Colombia', id: 'CO' },
  { groupa: 'Group number 1.2', label: 'Comoros', id: 'KM' },
  { groupa: 'Group number 1.2', label: 'Congo', id: 'CG' },
  {
    groupa: 'Group number 1.2',
    label: 'Congo, The Democratic Republic of the',
    id: 'CD',
  },
  { groupa: 'Group number 1.2', label: 'Cook Islands', id: 'CK' },
  { groupa: 'Group number 1.2', label: 'Costa Rica', id: 'CR' },
  { groupa: 'Group number 1.2', label: "Cote D'Ivoire", id: 'CI' },
  { groupa: 'Group number 1.3', label: 'Croatia', id: 'HR' },
  { groupa: 'Group number 1.3', label: 'Cuba', id: 'CU' },
  { groupa: 'Group number 1.3', label: 'Cyprus', id: 'CY' },
  { groupa: 'Group number 1.3', label: 'Czech Republic', id: 'CZ' },
  { groupa: 'Group number 1.3', label: 'Denmark', id: 'DK' },
  { groupa: 'Group number 1.3', label: 'Djibouti', id: 'DJ' },
  { groupa: 'Group number 1.3', label: 'Dominica', id: 'DM' },

  { groupa: 'Group number 2', label: 'Dominican Republic', id: 'DO' },
  { groupa: 'Group number 2', label: 'Ecuador', id: 'EC' },
  { groupa: 'Group number 2', label: 'Egypt', id: 'EG' },
  { groupa: 'Group number 2', label: 'El Salvador', id: 'SV' },
  { groupa: 'Group number 2', label: 'Equatorial Guinea', id: 'GQ' },
  { groupa: 'Group number 2', label: 'Eritrea', id: 'ER' },
  { groupa: 'Group number 2', label: 'Estonia', id: 'EE' },
  { groupa: 'Group number 2', label: 'Ethiopia', id: 'ET' },
  { groupa: 'Group number 2', label: 'Falkland Islands (Malvinas)', id: 'FK' },
  { groupa: 'Group number 2', label: 'Faroe Islands', id: 'FO' },
  { groupa: 'Group number 2', label: 'Fiji', id: 'FJ' },
  { groupa: 'Group number 2', label: 'Finland', id: 'FI' },
  { groupa: 'Group number 2', label: 'France', id: 'FR' },
  { groupa: 'Group number 2', label: 'French Guiana', id: 'GF' },
  { groupa: 'Group number 2', label: 'French Polynesia', id: 'PF' },
  { groupa: 'Group number 2', label: 'French Southern Territories', id: 'TF' },
  { groupa: 'Group number 2', label: 'Gabon', id: 'GA' },
  { groupa: 'Group number 2', label: 'Gambia', id: 'GM' },
  { groupa: 'Group number 2', label: 'Georgia', id: 'GE' },
  { groupa: 'Group number 2', label: 'Germany', id: 'DE' },
  { groupa: 'Group number 2', label: 'Ghana', id: 'GH' },
  { groupa: 'Group number 2', label: 'Gibraltar', id: 'GI' },
  { groupa: 'Group number 2', label: 'Greece', id: 'GR' },
  { groupa: 'Group number 2', label: 'Greenland', id: 'GL' },
  { groupa: 'Group number 2', label: 'Grenada', id: 'GD' },
  { groupa: 'Group number 2', label: 'Guadeloupe', id: 'GP' },
  { groupa: 'Group number 2', label: 'Guam', id: 'GU' },
  { groupa: 'Group number 2', label: 'Guatemala', id: 'GT' },
  { groupa: 'Group number 2', label: 'Guernsey', id: 'GG' },
  { groupa: 'Group number 2', label: 'Guinea', id: 'GN' },
  { groupa: 'Group number 2', label: 'Guinea-Bissau', id: 'GW' },
  { groupa: 'Group number 2', label: 'Guyana', id: 'GY' },
  { groupa: 'Group number 2', label: 'Haiti', id: 'HT' },
  {
    groupa: 'Group number 2',
    label: 'Heard Island and Mcdonald Islands',
    id: 'HM',
  },
  {
    groupa: 'Group number 2',
    label: 'Holy See (Vatican City State)',
    id: 'VA',
  },
  { groupa: 'Group number 2', label: 'Honduras', id: 'HN' },
  { groupa: 'Group number 2', label: 'Hong Kong', id: 'HK' },
  { groupa: 'Group number 2', label: 'Hungary', id: 'HU' },
  { groupa: 'Group number 2', label: 'Iceland', id: 'IS' },
  { groupa: 'Group number 2', label: 'India', id: 'IN' },
  { groupa: 'Group number 2', label: 'Indonesia', id: 'ID' },
  { groupa: 'Group number 3', label: 'Iran, Islamic Republic Of', id: 'IR' },
  { groupa: 'Group number 3', label: 'Iraq', id: 'IQ' },
  { groupa: 'Group number 3', label: 'Ireland', id: 'IE' },
  { groupa: 'Group number 3', label: 'Isle of Man', id: 'IM' },
  { groupa: 'Group number 3', label: 'Israel', id: 'IL' },
  { groupa: 'Group number 3', label: 'Italy', id: 'IT' },
  { groupa: 'Group number 3', label: 'Jamaica', id: 'JM' },
  { groupa: 'Group number 3', label: 'Japan', id: 'JP' },
  { groupa: 'Group number 3', label: 'Jersey', id: 'JE' },
  { groupa: 'Group number 3', label: 'Jordan', id: 'JO' },
  { groupa: 'Group number 3', label: 'Kazakhstan', id: 'KZ' },
  { groupa: 'Group number 3', label: 'Kenya', id: 'KE' },
  { groupa: 'Group number 3', label: 'Kiribati', id: 'KI' },
  {
    groupa: 'Group number 3',
    label: "Korea, Democratic People'S Republic of",
    id: 'KP',
  },
  { groupa: 'Group number 3', label: 'Korea, Republic of', id: 'KR' },
  { groupa: 'Group number 3', label: 'Kuwait', id: 'KW' },
  { groupa: 'Group number 3', label: 'Kyrgyzstan', id: 'KG' },
  {
    groupa: 'Group number 3',
    label: "Lao People'S Democratic Republic",
    id: 'LA',
  },
  { groupa: 'Group number 3', label: 'Latvia', id: 'LV' },
  { groupa: 'Group number 3', label: 'Lebanon', id: 'LB' },
  { groupa: 'Group number 3', label: 'Lesotho', id: 'LS' },
  { groupa: 'Group number 3', label: 'Liberia', id: 'LR' },
  { groupa: 'Group number 3', label: 'Libyan Arab Jamahiriya', id: 'LY' },
  { groupa: 'Group number 3', label: 'Liechtenstein', id: 'LI' },
  { groupa: 'Group number 3', label: 'Lithuania', id: 'LT' },
  { groupa: 'Group number 3', label: 'Luxembourg', id: 'LU' },
  { groupa: 'Group number 3', label: 'Macao', id: 'MO' },
  {
    groupa: 'Group number 3',
    label: 'Macedonia, The Former Yugoslav Republic of',
    id: 'MK',
  },
  { groupa: 'Group number 3', label: 'Madagascar', id: 'MG' },
  { groupa: 'Group number 3', label: 'Malawi', id: 'MW' },
  { groupa: 'Group number 3', label: 'Malaysia', id: 'MY' },
  { groupa: 'Group number 3', label: 'Maldives', id: 'MV' },
  { groupa: 'Group number 3', label: 'Mali', id: 'ML' },
  { groupa: 'Group number 3', label: 'Malta', id: 'MT' },
  { groupa: 'Group number 3', label: 'Marshall Islands', id: 'MH' },
  { groupa: 'Group number 3', label: 'Martinique', id: 'MQ' },
  { groupa: 'Group number 3', label: 'Mauritania', id: 'MR' },
  { groupa: 'Group number 3', label: 'Mauritius', id: 'MU' },
  { groupa: 'Group number 3', label: 'Mayotte', id: 'YT' },
  { groupa: 'Group number 3', label: 'Mexico', id: 'MX' },
  {
    groupa: 'Group number 3',
    label: 'Micronesia, Federated States of',
    id: 'FM',
  },
  { groupa: 'Group number 3', label: 'Moldova, Republic of', id: 'MD' },
  { groupa: 'Group number 3', label: 'Monaco', id: 'MC' },
  { groupa: 'Group number 3', label: 'Mongolia', id: 'MN' },
  { groupa: 'Group number 3', label: 'Montserrat', id: 'MS' },
  { groupa: 'Group number 3', label: 'Morocco', id: 'MA' },
  { groupa: 'Group number 3', label: 'Mozambique', id: 'MZ' },
  { groupa: 'Group number 3', label: 'Myanmar', id: 'MM' },
  { groupa: 'Group number 3', label: 'Namibia', id: 'NA' },
  { groupa: 'Group number 3', label: 'Nauru', id: 'NR' },
  { groupa: 'Group number 3', label: 'Nepal', id: 'NP' },
  { groupa: 'Group number 3', label: 'Netherlands', id: 'NL' },
  { groupa: 'Group number 3', label: 'Netherlands Antilles', id: 'AN' },
  { groupa: 'Group number 4', label: 'New Caledonia', id: 'NC' },
  { groupa: 'Group number 4', label: 'New Zealand', id: 'NZ' },
  { groupa: 'Group number 4', label: 'Nicaragua', id: 'NI' },
  { groupa: 'Group number 4', label: 'Niger', id: 'NE' },
  { groupa: 'Group number 4', label: 'Nigeria', id: 'NG' },
  { groupa: 'Group number 4', label: 'Niue', id: 'NU' },
  { groupa: 'Group number 4', label: 'Norfolk Island', id: 'NF' },
  { groupa: 'Group number 4', label: 'Northern Mariana Islands', id: 'MP' },
  { groupa: 'Group number 4', label: 'Norway', id: 'NO' },
  { groupa: 'Group number 4', label: 'Oman', id: 'OM' },
  { groupa: 'Group number 4', label: 'Pakistan', id: 'PK' },
  { groupa: 'Group number 4', label: 'Palau', id: 'PW' },
  {
    groupa: 'Group number 4',
    label: 'Palestinian Territory, Occupied',
    id: 'PS',
  },
  { groupa: 'Group number 4', label: 'Panama', id: 'PA' },
  { groupa: 'Group number 4', label: 'Papua New Guinea', id: 'PG' },
  { groupa: 'Group number 4', label: 'Paraguay', id: 'PY' },
  { groupa: 'Group number 4', label: 'Peru', id: 'PE' },
  { groupa: 'Group number 4', label: 'Philippines', id: 'PH' },
  { groupa: 'Group number 4', label: 'Pitcairn', id: 'PN' },
  { groupa: 'Group number 4', label: 'Poland', id: 'PL' },
  { groupa: 'Group number 4', label: 'Portugal', id: 'PT' },
  { groupa: 'Group number 4', label: 'Puerto Rico', id: 'PR' },
  { groupa: 'Group number 4', label: 'Qatar', id: 'QA' },
  { groupa: 'Group number 4', label: 'Reunion', id: 'RE' },
  { groupa: 'Group number 4', label: 'Romania', id: 'RO' },
  { groupa: 'Group number 4', label: 'Russian Federation', id: 'RU' },
  { groupa: 'Group number 4', label: 'RWANDA', id: 'RW' },
  { groupa: 'Group number 4', label: 'Saint Helena', id: 'SH' },
  { groupa: 'Group number 4', label: 'Saint Kitts and Nevis', id: 'KN' },
  { groupa: 'Group number 4', label: 'Saint Lucia', id: 'LC' },
  { groupa: 'Group number 4', label: 'Saint Pierre and Miquelon', id: 'PM' },
  {
    groupa: 'Group number 4',
    label: 'Saint Vincent and the Grenadines',
    id: 'VC',
  },
  { groupa: 'Group number 4', label: 'Samoa', id: 'WS' },
  { groupa: 'Group number 4', label: 'San Marino', id: 'SM' },
  { groupa: 'Group number 4', label: 'Sao Tome and Principe', id: 'ST' },
  { groupa: 'Group number 4', label: 'Saudi Arabia', id: 'SA' },
  { groupa: 'Group number 4', label: 'Senegal', id: 'SN' },
  { groupa: 'Group number 4', label: 'Serbia and Montenegro', id: 'CS' },
  { groupa: 'Group number 4', label: 'Seychelles', id: 'SC' },
  { groupa: 'Group number 4', label: 'Sierra Leone', id: 'SL' },
  { groupa: 'Group number 4', label: 'Singapore', id: 'SG' },
  { groupa: 'Group number 4', label: 'Slovakia', id: 'SK' },
  { groupa: 'Group number 4', label: 'Slovenia', id: 'SI' },
  { groupa: 'Group number 4', label: 'Solomon Islands', id: 'SB' },
  { groupa: 'Group number 4', label: 'Somalia', id: 'SO' },
  { groupa: 'Group number 4', label: 'South Africa', id: 'ZA' },
  {
    groupa: 'Group number 4',
    label: 'South Georgia and the South Sandwich Islands',
    id: 'GS',
  },
  { groupa: 'Group number 4', label: 'Spain', id: 'ES' },
  { groupa: 'Group number 4', label: 'Sri Lanka', id: 'LK' },
  { groupa: 'Group number 4', label: 'Sudan', id: 'SD' },
  { groupa: 'Group number 4', label: 'Surilabel', id: 'SR' },
  { groupa: 'Group number 4', label: 'Svalbard and Jan Mayen', id: 'SJ' },
  { groupa: 'Group number 4', label: 'Swaziland', id: 'SZ' },
  { groupa: 'Group number 4', label: 'Sweden', id: 'SE' },
  { groupa: 'Group number 4', label: 'Switzerland', id: 'CH' },
  { groupa: 'Group number 4', label: 'Syrian Arab Republic', id: 'SY' },
  { groupa: 'Group number 4', label: 'Taiwan, Province of China', id: 'TW' },
  { groupa: 'Group number 4', label: 'Tajikistan', id: 'TJ' },
  {
    groupa: 'Group number 4',
    label: 'Tanzania, United Republic of',
    id: 'TZ',
  },
  { groupa: 'Group number 4', label: 'Thailand', id: 'TH' },
  { groupa: 'Group number 4', label: 'Timor-Leste', id: 'TL' },
  { groupa: 'Group number 4', label: 'Togo', id: 'TG' },
  { groupa: 'Group number 4', label: 'Tokelau', id: 'TK' },
  { groupa: 'Group number 4', label: 'Tonga', id: 'TO' },
  { groupa: 'Group number 4', label: 'Trinidad and Tobago', id: 'TT' },
  { groupa: 'Group number 4', label: 'Tunisia', id: 'TN' },
  { groupa: 'Group number 4', label: 'Turkey', id: 'TR' },
  { groupa: 'Group number 4', label: 'Turkmenistan', id: 'TM' },
  { groupa: 'Group number 4', label: 'Turks and Caicos Islands', id: 'TC' },
  { groupa: 'Group number 4', label: 'Tuvalu', id: 'TV' },
  { groupa: 'Group number 4', label: 'Uganda', id: 'UG' },
  { groupa: 'Group number 4', label: 'Ukraine', id: 'UA' },
  { groupa: 'Group number 4', label: 'United Arab Emirates', id: 'AE' },
  { groupa: 'Group number 4', label: 'United Kingdom', id: 'GB' },
  { groupa: 'Group number 4', label: 'United States', id: 'US' },
  {
    groupa: 'Group number 4',
    label: 'United States Minor Outlying Islands',
    id: 'UM',
  },
  { groupa: 'Group number 4', label: 'Uruguay', id: 'UY' },
  { groupa: 'Group number 4', label: 'Uzbekistan', id: 'UZ' },
  { groupa: 'Group number 4', label: 'Vanuatu', id: 'VU' },
  { groupa: 'Group number 4', label: 'Venezuela', id: 'VE' },
  { groupa: 'Group number 4', label: 'Viet Nam', id: 'VN' },
  { groupa: 'Group number 4', label: 'Virgin Islands, British', id: 'VG' },
  { groupa: 'Group number 4', label: 'Virgin Islands, U.S.', id: 'VI' },
  { groupa: 'Group number 4', label: 'Wallis and Futuna', id: 'WF' },
  { groupa: 'Group number 4', label: 'Western Sahara', id: 'EH' },
  { groupa: 'Group number 4', label: 'Yemen', id: 'YE' },
  { groupa: 'Group number 4', label: 'Zambia', id: 'ZM' },
  { groupa: 'Group number 4', label: 'Zimbabwe', id: 'ZW' },
];
